/* ==========================================================================
   Gato Lab — traducciones de los datos técnicos de las fichas
   --------------------------------------------------------------------------
   Los textos de cierre, volumen, goma y construcción se escriben en castellano
   en el panel (content/shoes.json). Aquí está su traducción al catalán, inglés
   y francés. Si un texto no aparece en esta lista, la web lo muestra tal cual
   (en castellano), así que al añadir un cierre o volumen nuevo en el panel
   conviene añadir aquí su traducción.
   js/app.js mezcla este objeto con su diccionario VOCAB al arrancar.
   ========================================================================== */
window.GatoLabVocab = {
  "cierre": {
    "1 velcro": {"ca":"1 velcro","en":"1 velcro strap","fr":"1 velcro"},
    "Cordones": {"ca":"Cordons","en":"Laces","fr":"Lacets"},
    "Cordones (CCS)": {"ca":"Cordons (CCS)","en":"Laces (CCS)","fr":"Lacets (CCS)"},
    "Cordones (Fast Lacing System)": {"ca":"Cordons (Fast Lacing System)","en":"Laces (Fast Lacing System)","fr":"Lacets (Fast Lacing System)"},
    "Cordones (Fast Lacing System) + velcro": {"ca":"Cordons (Fast Lacing System) + velcro","en":"Laces (Fast Lacing System) + velcro","fr":"Lacets (Fast Lacing System) + velcro"},
    "Cordones (asimétricos)": {"ca":"Cordons (asimètrics)","en":"Laces (asymmetric)","fr":"Lacets (asymétriques)"},
    "Cordones (desplazados)": {"ca":"Cordons (desplaçats)","en":"Laces (offset)","fr":"Lacets (décalés)"},
    "Cordones (doble lazada a contraste)": {"ca":"Cordons (doble llaçada en contrast)","en":"Laces (contrasting double lacing)","fr":"Lacets (double laçage contrasté)"},
    "Cordones (sistema de cordino patentado Mythos)": {"ca":"Cordons (sistema de cordino patentat Mythos)","en":"Laces (patented Mythos lacing system)","fr":"Lacets (système de laçage breveté Mythos)"},
    "Cordones (sistema de cordón descentrado con tensores V2 Rand en el talón)": {"ca":"Cordons (sistema de cordó descentrat amb tensors V2 Rand al taló)","en":"Laces (off-centre lacing with V2 Rand heel tensioners)","fr":"Lacets (laçage décentré avec tendeurs V2 Rand au talon)"},
    "Cordones (talón regulable, se puede acortar o anudar)": {"ca":"Cordons (taló regulable, es pot escurçar o nuar)","en":"Laces (adjustable heel, can be shortened or knotted)","fr":"Lacets (talon réglable, peut être raccourci ou noué)"},
    "Cordones + Wrap Rand": {"ca":"Cordons + Wrap Rand","en":"Laces + Wrap Rand","fr":"Lacets + Wrap Rand"},
    "Cordones + cintas laterales": {"ca":"Cordons + cintes laterals","en":"Laces + side tapes","fr":"Lacets + bandes latérales"},
    "Cordones + velcro": {"ca":"Cordons + velcro","en":"Laces + velcro","fr":"Lacets + velcro"},
    "Cordones + velcro (Speed Lace)": {"ca":"Cordons + velcro (Speed Lace)","en":"Laces + velcro (Speed Lace)","fr":"Lacets + velcro (Speed Lace)"},
    "Cordones rápidos (Salomon Quicklace)": {"ca":"Cordons ràpids (Salomon Quicklace)","en":"Quick laces (Salomon Quicklace)","fr":"Lacets rapides (Salomon Quicklace)"},
    "Cordón rápido (Fast Lacing System)": {"ca":"Cordó ràpid (Fast Lacing System)","en":"Quick lace (Fast Lacing System)","fr":"Lacet rapide (Fast Lacing System)"},
    "Correa superior + elástico inferior": {"ca":"Corretja superior + elàstic inferior","en":"Top strap + lower elastic","fr":"Sangle supérieure + élastique inférieur"},
    "Doble correa": {"ca":"Doble corretja","en":"Double strap","fr":"Double sangle"},
    "Doble correa (velcro)": {"ca":"Doble corretja (velcro)","en":"Double strap (velcro)","fr":"Double sangle (velcro)"},
    "Doble correa (velcro) + Wrap Rand": {"ca":"Doble corretja (velcro) + Wrap Rand","en":"Double strap (velcro) + Wrap Rand","fr":"Double sangle (velcro) + Wrap Rand"},
    "Doble correa (velcro) + lengüeta elástica": {"ca":"Doble corretja (velcro) + llengüeta elàstica","en":"Double strap (velcro) + elastic tongue","fr":"Double sangle (velcro) + languette élastique"},
    "Doble velcro": {"ca":"Doble velcro","en":"Double velcro","fr":"Double velcro"},
    "Doble velcro (sistema DTS, Differentiated Tension System)": {"ca":"Doble velcro (sistema DTS, Differentiated Tension System)","en":"Double velcro (DTS, Differentiated Tension System)","fr":"Double velcro (système DTS, Differentiated Tension System)"},
    "Doble velcro con sistema de tensión activa (V-Tension)": {"ca":"Doble velcro amb sistema de tensió activa (V-Tension)","en":"Double velcro with active tension system (V-Tension)","fr":"Double velcro avec système de tension active (V-Tension)"},
    "Doble velcro cruzado (sistema TA, Toe Abductor)": {"ca":"Doble velcro creuat (sistema TA, Toe Abductor)","en":"Crossed double velcro (TA system, Toe Abductor)","fr":"Double velcro croisé (système TA, Toe Abductor)"},
    "Doble velcro de 2 zonas": {"ca":"Doble velcro de 2 zones","en":"Two-zone double velcro","fr":"Double velcro à 2 zones"},
    "Elástico": {"ca":"Elàstic","en":"Elastic","fr":"Élastique"},
    "Elástico (slipper)": {"ca":"Elàstic (slipper)","en":"Elastic (slipper)","fr":"Élastique (slipper)"},
    "Elástico + velcro": {"ca":"Elàstic + velcro","en":"Elastic + velcro","fr":"Élastique + velcro"},
    "Nano Strap System (3 modos de ajuste)": {"ca":"Nano Strap System (3 modes d'ajust)","en":"Nano Strap System (3 fit modes)","fr":"Nano Strap System (3 modes de serrage)"},
    "Sin cierre (slipper elástico REB)": {"ca":"Sense tancament (slipper elàstic REB)","en":"No closure (REB elastic slipper)","fr":"Sans fermeture (slipper élastique REB)"},
    "Sin cierre (slipper)": {"ca":"Sense tancament (slipper)","en":"No closure (slipper)","fr":"Sans fermeture (slipper)"},
    "Slipper (doble entrada elástica)": {"ca":"Slipper (doble entrada elàstica)","en":"Slipper (double elastic opening)","fr":"Slipper (double ouverture élastique)"},
    "Slipper (elástico)": {"ca":"Slipper (elàstic)","en":"Slipper (elastic)","fr":"Slipper (élastique)"},
    "Slipper (entrada elástica, sin cierre)": {"ca":"Slipper (entrada elàstica, sense tancament)","en":"Slipper (elastic opening, no closure)","fr":"Slipper (ouverture élastique, sans fermeture)"},
    "Slipper (sin cierre)": {"ca":"Slipper (sense tancament)","en":"Slipper (no closure)","fr":"Slipper (sans fermeture)"},
    "Slipper (velcro superior)": {"ca":"Slipper (velcro superior)","en":"Slipper (top velcro)","fr":"Slipper (velcro supérieur)"},
    "Slipper elástico": {"ca":"Slipper elàstic","en":"Elastic slipper","fr":"Slipper élastique"},
    "Triple correa (VCR)": {"ca":"Triple corretja (VCR)","en":"Triple strap (VCR)","fr":"Triple sangle (VCR)"},
    "Velcro": {"ca":"Velcro","en":"Velcro","fr":"Velcro"},
    "Velcro (1 correa ancha)": {"ca":"Velcro (1 corretja ampla)","en":"Velcro (1 wide strap)","fr":"Velcro (1 sangle large)"},
    "Velcro (1 correa)": {"ca":"Velcro (1 corretja)","en":"Velcro (1 strap)","fr":"Velcro (1 sangle)"},
    "Velcro (1 correa, cierre triple horquilla)": {"ca":"Velcro (1 corretja, tancament de triple forquilla)","en":"Velcro (1 strap, triple-fork closure)","fr":"Velcro (1 sangle, fermeture à triple fourche)"},
    "Velcro (2 correas cruzadas)": {"ca":"Velcro (2 corretges creuades)","en":"Velcro (2 crossed straps)","fr":"Velcro (2 sangles croisées)"},
    "Velcro (2 correas)": {"ca":"Velcro (2 corretges)","en":"Velcro (2 straps)","fr":"Velcro (2 sangles)"},
    "Velcro (2 correas, formato slipper)": {"ca":"Velcro (2 corretges, format slipper)","en":"Velcro (2 straps, slipper style)","fr":"Velcro (2 sangles, format slipper)"},
    "Velcro (3 correas)": {"ca":"Velcro (3 corretges)","en":"Velcro (3 straps)","fr":"Velcro (3 sangles)"},
    "Velcro (Draxtor)": {"ca":"Velcro (Draxtor)","en":"Velcro (Draxtor)","fr":"Velcro (Draxtor)"},
    "Velcro (Wrap Rand)": {"ca":"Velcro (Wrap Rand)","en":"Velcro (Wrap Rand)","fr":"Velcro (Wrap Rand)"},
    "Velcro (Z)": {"ca":"Velcro (Z)","en":"Velcro (Z)","fr":"Velcro (Z)"},
    "Velcro (Z-strap doble)": {"ca":"Velcro (Z-strap doble)","en":"Velcro (double Z-strap)","fr":"Velcro (double Z-strap)"},
    "Velcro (calcetín EvoWrap + correa)": {"ca":"Velcro (mitjó EvoWrap + corretja)","en":"Velcro (EvoWrap sock + strap)","fr":"Velcro (chaussette EvoWrap + sangle)"},
    "Velcro (correa ancha con ajuste elástico de tobillo)": {"ca":"Velcro (corretja ampla amb ajust elàstic al turmell)","en":"Velcro (wide strap with elastic ankle fit)","fr":"Velcro (sangle large avec serrage élastique à la cheville)"},
    "Velcro (correa ancha)": {"ca":"Velcro (corretja ampla)","en":"Velcro (wide strap)","fr":"Velcro (sangle large)"},
    "Velcro (correa ancha, ajustable hasta 2 tallas)": {"ca":"Velcro (corretja ampla, ajustable fins a 2 talles)","en":"Velcro (wide strap, adjustable up to 2 sizes)","fr":"Velcro (sangle large, réglable jusqu'à 2 pointures)"},
    "Velcro (correa trasera autoadherente)": {"ca":"Velcro (corretja posterior autoadherent)","en":"Velcro (self-adhesive rear strap)","fr":"Velcro (sangle arrière auto-agrippante)"},
    "Velcro (correa única con D-ring)": {"ca":"Velcro (corretja única amb D-ring)","en":"Velcro (single strap with D-ring)","fr":"Velcro (sangle unique avec anneau en D)"},
    "Velcro (correa única tipo z-strap)": {"ca":"Velcro (corretja única tipus z-strap)","en":"Velcro (single z-strap)","fr":"Velcro (sangle unique type z-strap)"},
    "Velcro (correa única)": {"ca":"Velcro (corretja única)","en":"Velcro (single strap)","fr":"Velcro (sangle unique)"},
    "Velcro (doble correa contrapuesta)": {"ca":"Velcro (doble corretja contraposada)","en":"Velcro (opposing double strap)","fr":"Velcro (double sangle opposée)"},
    "Velcro (doble correa cruzada)": {"ca":"Velcro (doble corretja creuada)","en":"Velcro (crossed double strap)","fr":"Velcro (double sangle croisée)"},
    "Velcro (doble correa)": {"ca":"Velcro (doble corretja)","en":"Velcro (double strap)","fr":"Velcro (double sangle)"},
    "Velcro (en V)": {"ca":"Velcro (en V)","en":"Velcro (V-shaped)","fr":"Velcro (en V)"},
    "Velcro (en Z)": {"ca":"Velcro (en Z)","en":"Velcro (Z-shaped)","fr":"Velcro (en Z)"},
    "Velcro (mono correa)": {"ca":"Velcro (monocorretja)","en":"Velcro (single strap)","fr":"Velcro (mono-sangle)"},
    "Velcro (solapa única, apertura ancha)": {"ca":"Velcro (solapa única, obertura ampla)","en":"Velcro (single flap, wide opening)","fr":"Velcro (rabat unique, large ouverture)"},
    "Velcro (triple correa)": {"ca":"Velcro (triple corretja)","en":"Velcro (triple strap)","fr":"Velcro (triple sangle)"},
    "Velcro (upper de calcetín)": {"ca":"Velcro (empenya tipus mitjó)","en":"Velcro (sock-style upper)","fr":"Velcro (tige type chaussette)"},
    "Velcro (upper híbrido de calcetín)": {"ca":"Velcro (empenya híbrida tipus mitjó)","en":"Velcro (hybrid sock-style upper)","fr":"Velcro (tige hybride type chaussette)"},
    "Velcro + banda elástica": {"ca":"Velcro + banda elàstica","en":"Velcro + elastic band","fr":"Velcro + bande élastique"},
    "Velcro con hebilla de doble punto de anclaje": {"ca":"Velcro amb sivella de doble punt d'ancoratge","en":"Velcro with dual-anchor buckle","fr":"Velcro avec boucle à double point d'ancrage"},
    "Velcro doble": {"ca":"Velcro doble","en":"Double velcro","fr":"Double velcro"},
    "Z-Cord integrado + correa personalizable": {"ca":"Z-Cord integrat + corretja personalitzable","en":"Integrated Z-Cord + customisable strap","fr":"Z-Cord intégré + sangle personnalisable"}
  },
  "volumen": {
    "Alternativo AV1 (más espacio en el lateral de la puntera, talón estrecho)": {"ca":"Alternatiu AV1 (més espai al lateral de la puntera, taló estret)","en":"Alternative AV1 (more room at the side of the toe box, narrow heel)","fr":"Alternatif AV1 (plus de place sur le côté de la pointe, talon étroit)"},
    "Alto": {"ca":"Alt","en":"High","fr":"Élevé"},
    "Alto (HV)": {"ca":"Alt (HV)","en":"High (HV)","fr":"Élevé (HV)"},
    "Alto (horma ancha)": {"ca":"Alt (horma ampla)","en":"High (wide last)","fr":"Élevé (forme large)"},
    "Amplio": {"ca":"Ampli","en":"Wide","fr":"Large"},
    "Amplio (el más ancho de los curvos Tenaya)": {"ca":"Ampli (el més ample dels corbats de Tenaya)","en":"Wide (the widest of Tenaya's downturned models)","fr":"Large (le plus large des modèles cambrés Tenaya)"},
    "Amplio (horma ancha)": {"ca":"Ampli (horma ampla)","en":"Wide (wide last)","fr":"Large (forme large)"},
    "Bajo": {"ca":"Baix","en":"Low","fr":"Bas"},
    "Bajo (LV)": {"ca":"Baix (LV)","en":"Low (LV)","fr":"Bas (LV)"},
    "Bajo (LV, horma de mujer)": {"ca":"Baix (LV, horma de dona)","en":"Low (LV, women's last)","fr":"Bas (LV, forme femme)"},
    "Bajo (LV, pie estrecho o mayor tensión)": {"ca":"Baix (LV, peu estret o més tensió)","en":"Low (LV, narrow feet or extra tension)","fr":"Bas (LV, pied étroit ou plus de tension)"},
    "Bajo (LV, un 6% menos que la estándar)": {"ca":"Baix (LV, un 6% menys que l'estàndard)","en":"Low (LV, 6% less than the standard)","fr":"Bas (LV, 6 % de moins que le standard)"},
    "Bajo (LV, ~6% menos volumen que el Defy estándar)": {"ca":"Baix (LV, ~6% menys volum que el Defy estàndard)","en":"Low (LV, ~6% less volume than the standard Defy)","fr":"Bas (LV, ~6 % de volume en moins que le Defy standard)"},
    "Bajo (horma LV específica)": {"ca":"Baix (horma LV específica)","en":"Low (dedicated LV last)","fr":"Bas (forme LV spécifique)"},
    "Bajo (horma estrecha de mujer)": {"ca":"Baix (horma estreta de dona)","en":"Low (narrow women's last)","fr":"Bas (forme étroite femme)"},
    "Bajo (horma estrecha)": {"ca":"Baix (horma estreta)","en":"Low (narrow last)","fr":"Bas (forme étroite)"},
    "Bajo (horma femenina)": {"ca":"Baix (horma femenina)","en":"Low (women's last)","fr":"Bas (forme féminine)"},
    "Disponible en horma ancha (volumen alto) y estrecha (volumen bajo/narrow)": {"ca":"Disponible en horma ampla (volum alt) i estreta (volum baix/narrow)","en":"Available in wide (high volume) and narrow (low volume) lasts","fr":"Disponible en forme large (grand volume) et étroite (petit volume)"},
    "Estrecho": {"ca":"Estret","en":"Narrow","fr":"Étroit"},
    "Estrecho, sin entresuela rígida": {"ca":"Estret, sense entresola rígida","en":"Narrow, no stiff midsole","fr":"Étroit, sans semelle intermédiaire rigide"},
    "Estándar": {"ca":"Estàndard","en":"Standard","fr":"Standard"},
    "Estándar (disponible también en versión WMNS con tallaje de mujer)": {"ca":"Estàndard (també disponible en versió WMNS amb talles de dona)","en":"Standard (also available in a WMNS version with women's sizing)","fr":"Standard (existe aussi en version WMNS avec pointures femme)"},
    "Estándar (disponible también en versión WMNS)": {"ca":"Estàndard (també disponible en versió WMNS)","en":"Standard (also available in a WMNS version)","fr":"Standard (existe aussi en version WMNS)"},
    "Estándar (fit estrecho y ancho disponibles)": {"ca":"Estàndard (ajust estret i ample disponibles)","en":"Standard (narrow and wide fits available)","fr":"Standard (versions étroite et large disponibles)"},
    "Estándar, horma neutra": {"ca":"Estàndard, horma neutra","en":"Standard, neutral last","fr":"Standard, forme neutre"},
    "Estándar, puntera redondeada": {"ca":"Estàndard, puntera arrodonida","en":"Standard, rounded toe","fr":"Standard, pointe arrondie"},
    "Estándar-ancho": {"ca":"Estàndard-ample","en":"Standard-wide","fr":"Standard-large"},
    "Medio (unisex)": {"ca":"Mitjà (unisex)","en":"Medium (unisex)","fr":"Moyen (unisexe)"},
    "Medio-alto (unisex)": {"ca":"Mitjà-alt (unisex)","en":"Medium-high (unisex)","fr":"Moyen-élevé (unisexe)"}
  },
  "goma": {
    "Goma cocida Tenaya": {"ca":"Goma cuita Tenaya","en":"Tenaya cured rubber","fr":"Gomme vulcanisée Tenaya"},
    "Goma propietaria So iLL": {"ca":"Goma pròpia So iLL","en":"So iLL proprietary rubber","fr":"Gomme propriétaire So iLL"},
    "Goma sintética Simond": {"ca":"Goma sintètica Simond","en":"Simond synthetic rubber","fr":"Gomme synthétique Simond"},
    "Unparallel RH (delantera) / RS (trasera), suela partida": {"ca":"Unparallel RH (davantera) / RS (posterior), sola partida","en":"Unparallel RH (front) / RS (rear), split sole","fr":"Unparallel RH (avant) / RS (arrière), semelle séparée"},
    "Unparallel RS (delantera) / RH (trasera), suela partida": {"ca":"Unparallel RS (davantera) / RH (posterior), sola partida","en":"Unparallel RS (front) / RH (rear), split sole","fr":"Unparallel RS (avant) / RH (arrière), semelle séparée"},
    "Unparallel VD (delantera) / RS (trasera), suela partida": {"ca":"Unparallel VD (davantera) / RS (posterior), sola partida","en":"Unparallel VD (front) / RS (rear), split sole","fr":"Unparallel VD (avant) / RS (arrière), semelle séparée"},
    "Vibram XS Edge (antepié 3.5mm) + XS Grip2 (talón 2mm)": {"ca":"Vibram XS Edge (avantpeu 3.5mm) + XS Grip2 (taló 2mm)","en":"Vibram XS Edge (forefoot 3.5mm) + XS Grip2 (heel 2mm)","fr":"Vibram XS Edge (avant-pied 3.5mm) + XS Grip2 (talon 2mm)"},
    "Vibram XS Edge + talón XS Grip2": {"ca":"Vibram XS Edge + taló XS Grip2","en":"Vibram XS Edge + XS Grip2 heel","fr":"Vibram XS Edge + talon XS Grip2"},
    "Vibram XS Grip / RX-1 Allround (mixta)": {"ca":"Vibram XS Grip / RX-1 Allround (mixta)","en":"Vibram XS Grip / RX-1 Allround (mixed)","fr":"Vibram XS Grip / RX-1 Allround (mixte)"},
    "Vibram XS Grip / RX-2 Techgrip (mixta)": {"ca":"Vibram XS Grip / RX-2 Techgrip (mixta)","en":"Vibram XS Grip / RX-2 Techgrip (mixed)","fr":"Vibram XS Grip / RX-2 Techgrip (mixte)"},
    "Vibram XS Grip2 (mitad delantera) + talón XS Grip2": {"ca":"Vibram XS Grip2 (meitat davantera) + taló XS Grip2","en":"Vibram XS Grip2 (front half) + XS Grip2 heel","fr":"Vibram XS Grip2 (moitié avant) + talon XS Grip2"},
    "Vibram XS Grip2 (talón IHC alta fricción)": {"ca":"Vibram XS Grip2 (taló IHC d'alta fricció)","en":"Vibram XS Grip2 (high-friction IHC heel)","fr":"Vibram XS Grip2 (talon IHC haute friction)"},
    "Vibram XS Grip2 + rand M50 (entresuela con fibra de carbono)": {"ca":"Vibram XS Grip2 + rand M50 (entresola amb fibra de carboni)","en":"Vibram XS Grip2 + M50 rand (carbon-fibre midsole)","fr":"Vibram XS Grip2 + rand M50 (semelle intermédiaire en fibre de carbone)"}
  },
  "construccion": {
    "Slip-lasted (flexible)": {"ca":"Slip-lasted (flexible)","en":"Slip-lasted (flexible)","fr":"Slip-lasted (souple)"},
    "Board-lasted (estructurada)": {"ca":"Board-lasted (estructurada)","en":"Board-lasted (structured)","fr":"Board-lasted (structurée)"},
    "Mixta (semi-estructurada)": {"ca":"Mixta (semiestructurada)","en":"Mixed (semi-structured)","fr":"Mixte (semi-structurée)"}
  },
  "forma": {
    "Neutra": {"ca":"Neutra","en":"Neutral","fr":"Neutre"}
  }
};
